/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function extractTextContent(content: Buffer, encoding: string): string

export interface FileInput {
  content: Buffer
  mimeType: string
  filename: string
}

export interface FileMetadata {
  name: string
  size: number
  processingTimeMs: number
  encoding: string
  textContent: string
}

export interface GroupedFiles {
  mimeType: string
  files: Array<FileMetadata>
}

export declare function processFiles(files: Array<FileInput>): Array<GroupedFiles>
